### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vsnain** [kareem983/Grocery-Shopping-System-App#1]
It would be great if you could add some documentation about how the whole app works, how to connect it to backend and create or delete admins.

**Comment by vsnain** [comment]
I added 2 products through the admin interface, but when i login using a normal user, it gives me an error: 
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.alpha.groceryshoppingsystem.Adapters.GridproductAdapter.getView(GridproductAdapter.java:64)

Please provide some documentation regarding the functioning of the app.

**Comment by kareem983** [comment]
Because I actually locked the database access. So anyone can't make any
changes in the data.

**Comment by kareem983** [comment]
> 
> 
> It would be great if you could add some documentation about how the whole app works, how to connect it to backend and create or delete admins.

okay Soon we will upgrade new version with new features including Documentation

**Comment by kareem983** [comment]
> 
> 
> > It would be great if you could add some documentation about how the whole app works, how to connect it to backend and create or delete admins.
> 
> okay Soon we will upgrade new version with new features including Documentation
