### ISSUE TITLE
Fatal error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 at com.example.groceryshoppingsystem.Adapters.GridproductAdapter.getView(GridproductAdapter.java:67)

### ISSUE THREAD

**Issue by nabilnazar** [kareem983/Grocery-Shopping-System-App#3]
https://stackoverflow.com/questions/69953841/android-studio-fatal-exception-app-getting-crashed-on-starting

**Comment by noorulain-dev** [comment]
I have the same error

**Comment by kareem983** [comment]
This is because i closed database access for every user for some specific reasons.
I will Resolve it soon.

**Comment by noorulain-dev** [comment]
Could you grant me access?

**Comment by nabilnazar** [comment]
> This is because i closed database access for every user for some specific reasons. I will Resolve it soon

I connected it with my firebase console and successfully logged in to application, but I couldn't see the products listed , however I saw different categories sections without products.

**Comment by rkjunior1998** [comment]
Hello how do you connect it to the firebase? Even though I have manually connected to firebase and registered a user but it keeps crashing and showing the error. Is it by putting the realtime database address into getReference() in GridProductAdapter?

> > This is because i closed database access for every user for some specific reasons. I will Resolve it soon
> 
> I connected it with my firebase console and successfully logged in to application, but I couldn't see the products listed , however I saw different categories sections without products.

@nabilnazar
